name: Deploy to Remote Docker
on:
  push:
    tags:
      - 'v*'
# DOCKER 环境变量
env:
  DOCKER_USERNAME: sqliuen@163.com
  DOCKER_PASSWORD: liu123...

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 20
      - name: 打包镜像, 上传 Docker Hub
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          TAG=$(echo "${{ github.ref }}" | sed -e 's|^refs/tags/||')
          REACT_WEB_TAG="react-web-h5-${TAG}"  # 在TAG中添加admin前缀
          echo "打包镜像: REACT_WEB_TAG is: $REACT_WEB_TAG"  # 调试输出
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build -t ${{ secrets.DOCKER_REPOSITORY }}:${REACT_WEB_TAG} -t ${{ secrets.DOCKER_REPOSITORY }}:react-web-h5-latest .
          docker push ${{ secrets.DOCKER_REPOSITORY }}:${REACT_WEB_TAG}
          docker push ${{ secrets.DOCKER_REPOSITORY }}:react-web-h5-latest

      # - name: 部署远程服务器
      #   uses: appleboy/ssh-action@v0.1.3
      #   with:
      #     host: ${{ secrets.SSH_HOST }}
      #     username: ${{ secrets.SSH_USERNAME }}
      #     key: ${{ secrets.SSH_PRIVATE_KEY }}
      #     run: |
      #       echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
      #       echo "Docker login successful"
      #       docker info  # 输出 Docker 系统信息，用于确认登录状态
      #     script: |
      #       cd /etc/uuvvuu
      #       docker-compose pull
      #       docker-compose up -d --force-recreate

